name: CollabVM Server 2 CI

on: [push, pull_request]

jobs:
  windows_x64:
    runs-on: windows-latest
    steps:
      - name: Build
        shell: powershell
        run: |
          New-Item collab-vm-win64.zip
      - name: Upload Release Asset
        uses: marvinpinto/action-automatic-releases@v0.2.2
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          automatic_release_tag: prerelease
          files: |
            test.txt
            collab-vm-win64.zip
