name: CollabVM Server 2 CI

on: [push, pull_request]

jobs:
  windows_x64:
    runs-on: windows-latest
    steps:
      - name: Build
        shell: powershell
        run: |
          mkdir build
          echo test > build\test
          try { Invoke-WebRequest https://github.com/Cosmic-Sans/collab-vm-server/releases/download/prerelease/hello -OutFile hello } catch {}
      - name: Upload Release Asset
        uses: marvinpinto/action-automatic-releases@v0.2.2
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          automatic_release_tag: prerelease
          files: |
            hello
            build/test
