name: CollabVM Server 2 CI

on: [push, pull_request]

jobs:
  windows_x64:
    runs-on: windows-latest
    steps:
      - name: Build
        shell: cmd
        run: |
          echo test > collab-vm-win64.zip
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          tag: prerelease
          artifact: collab-vm-win64.zip
